# Generated by Django 5.1.3 on 2024-12-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='contacts_app.contact'),
        ),
    ]
