# Generated by Django 5.1.4 on 2024-12-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_subtask_contact_user_alter_contact_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='taskContainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.task'),
        ),
    ]
