# Generated by Django 5.1.3 on 2024-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
        ('users_app', '0002_userprofile_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='tasks_app.task'),
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
