# Generated by Django 5.1.4 on 2024-12-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_subtask_taskcontainer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'verbose_name': 'Subtask', 'verbose_name_plural': 'Subtasks'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
