# Generated by Django 5.1.3 on 2024-12-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_contact_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
