# Generated by Django 5.1.3 on 2024-12-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'To Do'), (1, 'In Progress'), (2, 'Await Feedback'), (3, 'Done')], default=0),
        ),
    ]
