# Generated by Django 5.1.3 on 2024-12-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_task_user'),
    ]

    operations = [
    ]
