# Generated by Django 5.1.3 on 2024-12-23 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0005_alter_contact_user'),
        ('tasks_app', '0005_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigneduserprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='AssignedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.contact')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(related_name='tasks', through='tasks_app.AssignedContact', to='contacts_app.contact'),
        ),
        migrations.DeleteModel(
            name='AssignedUser',
        ),
        migrations.DeleteModel(
            name='AssignedUserProfile',
        ),
    ]
