# Generated by Django 5.1.3 on 2024-12-22 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_alter_contact_email'),
        ('users_app', '0003_remove_task_subtasks_remove_task_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='users_app.userprofile'),
            preserve_default=False,
        ),
    ]
