# Generated by Django 5.1.3 on 2024-12-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_contact_user'),
        ('users_app', '0003_remove_task_subtasks_remove_task_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.userprofile'),
        ),
    ]
