# Generated by Django 5.1.3 on 2024-12-22 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0004_alter_contact_user'),
        ('users_app', '0003_remove_task_subtasks_remove_task_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users_app.userprofile'),
            preserve_default=False,
        ),
    ]
